# Generated by Django 3.1.1 on 2020-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('seconds', models.PositiveIntegerField()),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('sending_time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
