# Generated by Django 3.1.1 on 2020-11-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmail',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='sending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
